language: node_js
node_js:
  - '10'
notifications:
  email: false
  slack: $SLACK_TOKEN
install:
  - yarn
script:
  - commitlint-travis
  - yarn global add codecov
  - yarn test
after_success:
  - codecov -f coverage/clover.xml
